### ISSUE TITLE
firedrake singularity-image built on kerguelen not working when used on gadi

### ISSUE THREAD

**Issue by sghelichkhani** [angus-g/firedrake-apptainer#1]
When using this [script](https://github.com/sghelichkhani/firedrake-apptainer/blob/petsc/firedrake-gcfixpetsc-build.def), with :

`/opt/apptainer/bin/apptainer build --fakeroot MYIMAGENAME.sif   firedrake-gcfixpetsc-build.def
`

on kerguelen and running the image on gadi using the following:

```
module load openmpi/4.1.2 singularity

export SINGULARITY_BIND="/apps/openmpi/4.1.2:/opt/ompi,/lib64/liblustreapi.so.1,/opt/pbs/default,/lib64/libxpmem.so.0,/lib64/librdmacm.so.1,/lib64/libibverbs.so.1,/apps/ucx/1.12.0,/opt/gdrcopy,/lib64/libmlx5.so.1,/apps/intel-oneapi:/opt/intel/oneapi,/lib64/libhwloc.so.15"
export LD_PRELOAD=$OPENMPI_ROOT/lib/libmpi.so
mpiexec -np ${PBS_NCPUS} -x SINGULARITY_BIND MYIMAGENAME.sif python fd-script.py

```

gamg diverges! The same script works fine with the available firedrake-singularity module. 

- Update: Changing to upstream petsc branch or any other petsc branch for that matter does not change the issue.

**Comment by angus-g** [comment]
You said this is reproducible with a simple forward run? Do you just need a single core run to get it to diverge, or is it with multiple cores?

**Comment by sghelichkhani** [comment]
I am closing this because the main issue was caused by gamg default variables. So it had nothing to do singularity images.
